# Generated by Django 4.2.7 on 2024-03-28 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('details', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
