# Generated by Django 4.2.7 on 2024-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['region'], name='stories_sto_region_a728b7_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['date'], name='stories_sto_date_ee93f6_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category'], name='stories_sto_categor_a6f1fa_idx'),
        ),
    ]
